# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Vitor M. B. Anjos
title: Intern @ Sensedia
email: vitorbartier@hotmail.com
# website: bartier.github.io

# Social links
# twitter_username: facespics
github_username:  bartier
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: vitorbartier
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Sobre mim
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Oi! Me chamo Vitor e atualmente faço estágio na Sensedia na área de Support & Operation. Atualmente estou estudando <mark>AWS</mark> e <mark>Go</mark>.

  Uso bastante no meu dia a dia: 
  <mark>Python</mark>
  <mark>Java</mark>
  <mark>Docker</mark>
  <mark>ShellScript</mark>
  <mark>Jenkins</mark>
  e a melhora ferramenta que resolva o problema. &#x1F603;

# Projects Section
projects_title: Alguns projetos

# Experience Section
experience_title: Experiência

# Education Section
education_title: Trajetória Acadêmica

# More Section
more_title: Um Pouco Mais Sobre Mim
more_content: | # this will include new lines to allow paragraphs
  Além de gostar de programação e tudo mais, tenho interesse em:
   - Counter-Strike: Global Offensive
   - Paz Mundial
   - Friends
   - Stranger Things

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
